### ISSUE TITLE
Chat message permalinks

### ISSUE THREAD

**Issue by mristau-wm** [jcraigk/kudochest#101]
Goals/Motivation: Unless a note is added when a kudo is given, it's not easy to figure out the context or reason behind why that kudo was given when looking at the dashboard or weekly report. Providing the message permalink URLs would allow the user to quickly view messages in context while preserving privacy.

**Comment by jcraigk** [comment]
This is a great idea. I think it makes sense to add a permalink column to the Dashboard for sure. This should theoretically also work in Discord, let's make sure we have as much feature parity across platforms when implementing this.

Keep in mind that not all tips will be associable with a chat permalink. For example, if giving using `/kudos` dialog, and the user has `announce_tip_sent` option set to false, there will be no chat visibility whatsoever. The `tip.source` field will be important here.

I just made some (mostly refactoring) improvements to the weekly reports in https://github.com/jcraigk/kudochest/pull/102, including adding the team digest section (previously only sent to admin) to the individual profile emails. I'm thinking it might make sense to add a section linking out to the last 5 tips a user received in the profile section but when it comes to the team section, I think we would omit individual permalinks because they may point to private channels.

**Comment by jcraigk** [comment]
Note: Discord does not seem to provide message-based permalinks, so this is a Slack-only feature.
