### ISSUE TITLE
great app ! I have question

### ISSUE THREAD

**Issue by kindh0623** [jcraigk/kudochest#140]
hello, I do not know what webserver etc. How can I use this features in discord? like other bots. 
https://discordbotlist.com/
here I can easily find bots and add to my server. but 
it seems this app(?) I cannot find there. 
I've spent 3hours how to adjust to my server. but I couldn't :( 
purpose is not for work, just to give each other karma between friends. 

thanks for your reading !

**Comment by jcraigk** [comment]
Hello, glad you like the app. As the wiki mentions (https://github.com/jcraigk/kudochest/wiki), KudoChest requires self-hosting the bot on your own hardware and hooking it up to your Discord guild by creating your own Discord App. The bots mentioned at https://discordbotlist.com/ are hosted by individual businesses who charge for their use. I used to do this with KudoChest, but I did not make enough money, so I open sourced the software.

If you can find someone who wants to start a business by hosting KudoChest and charging for it, I would be happy to see that happen! Otherwise, each person must setup their own server.
