### ISSUE TITLE
Per-profile announcement settings

### ISSUE THREAD

**Issue by brand-it** [jcraigk/kudochest#69]
Allow each user to decided if their kudos are posted publicly on a public channel. This could be nice if you want to give kudos to some one but not brag about how awesome your giving is

**Comment by jcraigk** [comment]
I think having two checkboxes available in the web UI at `/profile-settings` would make sense. They would be checked by default:

```
[X] Announce when I give kudos
[X] Announce when I receive kudos
```

We'd have to take into account that some kudos gifts are to a group of users (like `@channel++`) and some response themes may include a list of those usernames, so we'd need to remove them from those lists specifically.

If the administrator has Response Mode set to `silent`, I think that should take precedence, meaning there is no announcement (or log only). These settings are for privacy-focused users to ensure that their name never comes up when the Response Mode / Log would otherwise display that.

We should also consider adding a checkbox to the `/kudos` dialog if Response Mode is not `silent`:

```
[X] Announce this in Slack
```

We should also consider adding a keyword to the keyword-based version like `@user++ silent` to prevent the public message.
